name: Application CI
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.11
                uses: actions/setup-java@v1
                with:
                    java-version: '11.x'
            -   name: Test with Maven
                env:
                    TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
                    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
                run: |
                    chmod +x mvnw
                    ./mvnw -B test
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
    prettier:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Node
                uses: actions/setup-node@v1
                with:
                    node-version: '10.x'
            -   run: npm install
            -   name: Check prettier
                run: npm run prettier:java:check
